export const FONTS = {
	fontSizeAntonio3XL: '80px',
	fontSizeAntonioXXL: '48px',
	fontSizeAntonioXL: '40px',
	fontSizeAntonioL: '28px',
	fontSizeAntonioM: '24px',
	fontSizeAntonioS: '20px',
	fontSizeSpartanXXXL: '15px',
	fontSizeSpartanXXL: '14px',
	fontSizeSpartanXL: '12px',
	fontSizeSpartanL: '11px',
	fontSizeSpartanM: '9px',
	fontSizeSpartanS: '8px',
	fontWeightBold: '700',
	fontWeightMedium: '500',
	fontWeightRegular: '400',
	lineHeightXL: '25px',
	lineHeightL: '22px',
	lineHeightM: '16px',
	letterSpacing4XL: ' 2.57px ',
	letterSpacing3XXL: ' 1.93px',
	letterSpacingXXL: ' 1.36px',
	letterSpacingXL: ' 1px',
	letterSpacingL: ' 0.73px',
	letterSpacingM: '-0.75px',
	letterSpacingS: '-0.9px',
	letterSpacingXS: '-1.05px',
	letterSpacingXXS: '-1.5px'
};
